-- AlterTable
ALTER TABLE "user_vehicle_stats" ADD COLUMN     "expiring_1y_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_1y_fitness" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_1y_insurance" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_1y_nationalPermit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_1y_pollution" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_1y_roadTax" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_1y_statePermit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_3m_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_3m_fitness" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_3m_insurance" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_3m_nationalPermit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_3m_pollution" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_3m_roadTax" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_3m_statePermit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_6m_count" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_6m_fitness" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_6m_insurance" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_6m_nationalPermit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_6m_pollution" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_6m_roadTax" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "expiring_6m_statePermit" INTEGER NOT NULL DEFAULT 0;
